= Huygens ING scaffold

== todo when starting a project using this scaffold

- [ ] `git clone [this repo] [your projectname]`
- [ ] `git remote rename origin scaffold`
- [ ] `git remote add origin [where you want to store your code]`
- [ ] `git push --set-upstream origin master`
- [ ] `grep -Ri scaffold *` and replace it with your project name
- [ ] edit package.json and fill in the administrative fields (name, licence etc.)
- [ ] `git commit -am "Start [projectname] using scaffold from [this repo]"`
- [ ] `git push origin master`
- [ ] start hacking :)

== vscode configuration

- [ ] install the tslint extension

== todo / features
- [x] uses yarn for npm install so we have less chance of irreproducable bugs between team members
- [x] buildbase container that contains all packages so we can be certain that a build can still be done 5 years from now.
- [x] Dockerfile that does not use FROM buildbase and removes node_modules after build so we have a small container
- [x] put node_modules at the root so everyone uses the same node_modules (without downloading) but we can mount the entire app module and we can override a module if we want to by doing a local npm/yarn install
- [x] express base site
  - [x] index file that links to the three different js-apps
  - [x] storybook dev middleware +
      test: docker-compose up, open browser on http://localhost:8080/build/storybook/ and edit the components/test.story.tsx [<- note! typescript] watch if it updates automatically
  - [x] unittest dev middleware (HMR) +
      test: docker-compose up, open browser on http://localhost:8080/build/tests.html and edit the actions/theModule.test.ts [<- note! typescript] watch if it updates automatically
  - [x] app dev middleware (HMR) +
      test: docker-compose up, open browser on http://localhost:8080/build/index.html and edit the actions/theModule.test.ts [<- note! typescript] watch if it updates automatically
  - [x] static file serving
- [x] compilation + prod static file server
  - [x] app
- [x] Promise
  - [x] typescript
  - [x] polyfill
- [x] fetch
  - [x] typescript
  - [x] polyfill
- [x] React + React-dom + Redux
  - [x] typescript
  - [x] static asset
    - [x] HMR (3)
    - [x] compiled
- [x] proxy through browsersync
  * [x] with https (and no funky chrome changes because it's self-signed, document what the user needs to do)
- typescript error report
  * compilation
    ** [x] storybook
    ** [x] unittests
    ** [x] full app
  * hmr
    ** [x] storybook
    ** [x] unittests
    ** [x] full app
- tslint report
  * in vscode
  * compilation
    ** [x] storybook
    ** [x] unittests
    ** [x] full app
  * *NOTE:* I can't get hmr reporting (tslint-loader) to work.

- [ ] fix that node_modules should have parts available outside container and parts inside container (c++ libs should be compiled in container, vscode should be able to reach typings outside container)
- [ ] storybook with knobs
- [ ] storybook with documentation
- [ ] simple router (test pushState with scroll position)
- [ ] remote urls are configured using env-variables
- [ ] can be proxied under subfolder (is configured using env-variable)
  * [ ] test base tag with 
    ** pushState
    ** css urls
    ** script urls
    ** image urls
    ** images/css loaded via react

- [x] ci run on saucelabs
- [ ] vscode debugger support (chrome)
- caching
  * [ ] js compiled with hash and served with infinite cache header (both in dev and prod mode)
  * [ ] base html knows the hashes and is served with hash based etag
- [ ] https://www.npmjs.com/package/finalhandler
- [ ] log all requests as json to the console in prod mode
- [x] fast container shutdown
- [ ] storybook alle .story files laten includen
- [ ] refresh if storybook config changes
- [ ] refresh if webpack config changes

Not gonna do for now: 

- [ ] debug server from vscode?
- [ ] storybook for user documentation?
- [ ] chrome live edit support?
- [ ] make http:// redirect to https://

= folder layout
See README's at lower levels for an explanation of what each folder does.
