= Timbuctoo GraphQL GUI

This project is developed to easily create / generate front-ends for the Timbuctoo project.

== Goal

The goal of this project is to be able to generate GUI's based on GraphQL schema definitions and make it customizable on different levels.

== Code (src/app)

=== Components

Contains the main code. `api.tsx` contains the interfaces needed to create a custom rendering.

[ditaa]
....
  +-------------------+
  |                   |                         +----------------------------+
  |   DataRenderer    |                         |                            |
  |                   +-----------------------> |    TimComponent            |
  |                   |                         |                            |
  +-------------------+                         |                            |
          ^                                     +----------------------------+
          |
          |
          |
          |
          |
          |
          |                                      +---------------------------+
          |                                      |                           |
          +--------------------------------------+   Entity                  |
                                                 |                           |
                                                 |                           |
                                                 +---------------------------+

....

The `Entity` uses the `DataRenderer` to render its contents. 
The `DataRenderer` uses `TimComponent`s to its fields.
`TimComponent` converts the data of the `DataRenderer` to a jsx element.
`entity.story.tsx` contains implementation examples how the code is used.

=== Support

Support contains the GraphQL implementation of the `DataRenderer`. 
This `DataRenderer` uses a `GraphQlRenderConfiguration`.
The configuration contains the way the data is how the data is rendered.

== How to test
1. run `npm install` in the root directory of the project.
1. run `docker-compose up`
1. surf to `https://localhost:8080` with your favorite browser. (Your browser might complain about the connection being not seccure, ignore the warning an find the way you can work around this problem in you favorite browser.)

== See also

GraphQL: http://graphql.org/learn/
The base of this project: https://github.com/HuygensING/js-scaffold
Timbuctoo: https://github.com/HuygensING/timbuctoo
